"""
Static schema map for V2 engines.
Keep in sync with KRIZZY_OPS_CRM Airtable base.
"""

SCHEMA = {
    "Leads_REI": [
        "External_Id",
        "Source",
        "Name",
        "Phone",
        "Address",
        "City",
        "State",
        "ZIP",
        "ARV",
        "Asking",
        "Repairs",
        "Spread",
        "Status",
        "Outbound_Status",
        "Ingest_TS",
        "address",  # Legacy field
    ],
    "Inbound_REI_Raw": [
        "Name",
        "Source",
        "External_Id",
        "ARV",
        "Asking",
        "Repairs",
        "Address",
        "City",
        "State",
        "ZIP",
        "Raw_Payload",
        "Status",
        "Error_Message",
    ],
    "GovCon Opportunities": [
        "External_Id",
        "Source",
        "Solicitation Number",
        "Title",
        "Agency",
        "NAICS",
        "Set_Aside",
        "Response_Deadline",
        "Estimated_Value",
        "Status",
    ],
    "Inbound_GovCon_Raw": [
        "External_Id",
        "Source",
        "Solicitation Number",
        "Title",
        "Agency",
        "NAICS",
        "Set_Aside",
        "Response_Deadline",
        "Estimated_Value",
        "Raw_Payload",
        "Status",
        "Error_Message",
    ],
    "REI_Buyers": [
        "Buyer_ID",
        "Name",
        "Phone",
        "Email",
        "Market_City",
        "Market_State",
        "ZIP_Codes",
        "Min_Price",
        "Max_Price",
        "Rehab_Appetite",
        "Strategy",
        "Tier",
        "Response_Rate",
        "Close_Rate",
        "Total_Deals_Closed",
        "Total_Contacted",
        "Opt_Out",
    ],
    "Outbound_Log": [
        "phone_number",
        "bucket",
        "message",
        "success",
        "timestamp",
        "error",
    ],
}
