services:
  - type: web
    name: krizzy-ops-web
    env: node
    plan: free
    buildCommand: "cd web && npm ci"
    startCommand: "cd web && node server.js"
    envVars:
      - key: PORT
        value: "10000"
      - key: DISCORD_WEBHOOK_OPS
        sync: false
      - key: DISCORD_WEBHOOK_ERRORS
        sync: false
      - key: DISCORD_WEBHOOK_TRADES
        sync: false
      - key: N8N_BASE_URL
        sync: false
      - key: N8N_API_KEY
        sync: false
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_MESSAGING_SERVICE_SID
        sync: false
      - key: SAM_SEARCH_API
        sync: false
      - key: FPDS_ATOM_FEED
        sync: false
      - key: UEI
        sync: false
      - key: CAGE_CODE
        sync: false
      - key: NAICS_WHITELIST
        sync: false

  - type: worker
    name: krizzy-ops-n8n
    env: docker
    plan: free
    dockerfilePath: worker/Dockerfile
