name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          ruff --version
          ruff check . || true
          black --version
          black --check . || true
      - name: Run tests
        env:
          AIRTABLE_API_KEY: dummy
          AIRTABLE_BASE_ID: appDummy
        run: |
          pytest -q
