name: CI

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with ruff
        run: |
          pip install ruff
          ruff check . --select E,F,W --ignore E501

      - name: Format check with black
        run: |
          pip install black
          black --check --line-length 100 .

      - name: Run pytest
        run: |
          pytest -v --cov=. --cov-report=term-missing --cov-report=xml
        env:
          AIRTABLE_API_KEY: test_key
          AIRTABLE_BASE_ID: test_base
          DISCORD_WEBHOOK_OPS: https://discord.com/api/webhooks/test
          DISCORD_WEBHOOK_ERRORS: https://discord.com/api/webhooks/test
          TWILIO_ACCOUNT_SID: test_sid
          TWILIO_AUTH_TOKEN: test_token
          TWILIO_MESSAGING_SERVICE_SID: test_service

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
